[project]
name = "redirector-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "python-dotenv",
  "discord.py",
  "python-telegram-bot",
]

